config/routes.rb
GiftsApplication::Application.routes.draw do

  resources :events
  resources :users
  resources :static_pages do
    get :search_artist, on: :collection, as: :search_artist
    get :search_zipcode, on: :collection, as: :search_zipcode
  end
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  match '/venues', to: 'static_pages#venues', via: 'get', as: 'venues'
  match '/artists', to: 'static_pages#artist', via: 'get', as: 'artists'
  match '/events', to: 'events#index', via: 'get', as: 'events'
  match '/signin', to: 'sessions#new', via: 'get', as: 'signin'
  match '/signup', to: 'users#new', via: 'get', as: 'signup'
  match '/signout', to: 'sessions#destroy', via: 'get', as: 'signout'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include ApiEndpoints

  def home
  end

  def artist
    @search = params['static_pages']['artist']
    if @search.empty?
      flash[:error] = 'Enter the name of a group or artist first!'
      redirect_to root_path
    else
      artist_response = get_artists_response_body({'name' => @search})
      if artist_response
        @artists = JSON.parse(artist_response)['Artists']
      else
        @artists = nil
      end
    end
  end

  def show
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/artist.html.erb
<div class="col-md-10 col-md-offset-1">
	<% if @artists %>
		<div class="panel panel-default">
			<div class="panel-heading"><h2>Search Results for: <span class="label label-info"><%= @search %></span></h2></div>
			<ul class="list-group">
				<% @artists.each do |artist| %>
					<li class="list-group-item"><h4><%= link_to artist['Name'], events_path( 'artistId' => artist['Id'], 'artistName' => artist['Name'] ) %></h4></li>
				<% end %>

				<% if @artists.empty? %>
					<li class="list-group-item"><h2 class="text-center">Sorry, no results</h2></li>
				<% end %>
			</ul>
		</div>
	<% else %>
		<h2 class="text-center">Sorry, no results</h2>
	<% end %>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron col-md-8 col-md-offset-2">
	<div class="container-fluid col-md-10 col-md-offset-1">
		<h1>Come Out And Jam</h1>
		<p>Search for events by artist or location</p>

		<div class="row-fluid">
			<%= form_for(:static_pages, :url => events_path, :html => { :method => :get, :class => "form-group form-inline" }) do |f| %>

				<%= f.submit "Search Location", class: "btn btn-large btn-primary"%>

				<div class="form-group">
					<%= f.label 'Zipcode', class: "sr-only"%>
					<%= f.text_field 'zipcode', class: "form-control", placeholder: "Enter Zip Code" %>
				</div>

			<% end %>
		</div>

		<div class="row-fluid">
			<%= form_for(:static_pages, :url => artists_path, :html => { :method => :get, :class => "form-group form-inline" }) do |f| %>

				<%= f.submit "Search Artist / Group", class: "btn btn-large btn-primary" %>

				<div class="form-group">
					<%= f.label 'Artist', class: "sr-only"%>
					<%= f.text_field 'artist', class: "form-control", placeholder: "Enter Artist / Group" %>
				</div>

			<% end %>
		</div>
	</div>
</div>