config/routes.rb
GiftsApplication::Application.routes.draw do

  resources :events
  resources :users
  resources :static_pages do
    get :search_artist, on: :collection, as: :search_artist
    get :search_zipcode, on: :collection, as: :search_zipcode
  end
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  match '/venues', to: 'static_pages#venues', via: 'get', as: 'venues'
  match '/artists', to: 'static_pages#artist', via: 'get', as: 'artists'
  match '/events', to: 'events#index', via: 'get', as: 'events'
  match '/signin', to: 'sessions#new', via: 'get', as: 'signin'
  match '/signup', to: 'users#new', via: 'get', as: 'signup'
  match '/signout', to: 'sessions#destroy', via: 'get', as: 'signout'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :email, :remember_token, :favorite_events
  has_many :events, dependent: :destroy
  has_secure_password

  before_save { downcase_email }
  before_create :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8, maximum: 24 }

  def downcase_email
    if !self.email.nil?
      self.email = email.downcase
    end
  end

  def User.hash(token)
  	return Digest::SHA1.hexdigest(token.to_s)
  end

  def User.new_remember_token
  	return SecureRandom.urlsafe_base64
  end

  def add_event_to_favorites(event)
    if self.favorite_events.nil?
      update_attribute(:favorite_events, event)
    end
  end

  private

	  def create_remember_token
	  	self.remember_token = User.hash(User.new_remember_token)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    super
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { 
          sign_in @user
          flash[:success] = 'Welcome!'
          redirect_to @user
        }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token(remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper

	def has_favorite_events?
		current_user.events.any?
	end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger"><%= pluralize(@user.errors.count, "error") %> in form:</div>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li> * <%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "sr-only" %><br />
    <%= f.text_field :name, class: "form-control", placeholder: 'Name' %>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "sr-only" %><br />
    <%= f.text_field :email, class: "form-control", placeholder: 'Email' %>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "sr-only" %><br />
    <%= f.password_field :password, class: "form-control", placeholder: 'Password' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, class: "sr-only" %><br />
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: 'Password Confirmation' %>
  </div>

  <%= f.submit "Create Account", class: "btn btn-large btn-primary btn-block" %>

<% end %>

app/views/users/_sign_in.html.erb
<%= form_for(:session, url: sessions_path) do |f| %>

	<div class="form-group">
		<%= f.label :email, class: "sr-only" %>
		<%= f.text_field :email, class: "form-control", placeholder: 'Email' %>
	</div>

	<div class="form-group">
		<%= f.label :password, class: "sr-only" %>
		<%= f.password_field :password, class: "form-control", placeholder: 'Password' %>
	</div>

	<%= f.submit "Submit", class: "btn btn-large btn-primary btn-block" %>
<% end %>
<br>
<%= link_to "New user? Sign up now!", signup_path, class: "btn btn-large btn-default btn-block" %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<div class="container-fluid">
	<h1 class="text-center">Sign Up</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/users/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<% if @user%>
		<div class="panel panel-default">
			<div class="panel-body">
				<h1 class="text-center">Information</h1>
				<div class="form-horizontal">
					<div class="form-group">
						<label class="col-md-2 control-label">Name:</label>
						<div class="col-md-10">
							<p class="form-control-static"><%= @user.name %></p>
						</div>
					</div>

					<div class="form-group">
						<label class="col-md-2 control-label">Email:</label>
						<div class="col-md-10">
							<p class="form-control-static"><%= @user.email %></p>
						</div>
					</div>
				</div>
				<% if @user.events.any? %>
					<div class="col-md-10 col-md-offset-1">
						<div class="panel panel-info">
							<div class="panel-heading">
								<h4 class="text-center">Favourite Events</h4>
							</div>
							<ul class="list-group">
								<% @user.events.each do |event| %>
									<li class="list-group-item">
										<h5><strong><%= event.venue_name %></strong></h5>
										<h5><%= Time.parse(event.date).strftime("%b %d, %Y") %></h5>
										<p><%= event.artist_names %></p>
										<%= button_to "Remove", event_path(event.id), method: :delete, class: "btn btn-danger btn-xs btn-block" %>
									</li>
								<% end %>
							</ul>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	<% else %>
		<p>User not found!</p>
	<% end %>
</div>