config/routes.rb
GiftsApplication::Application.routes.draw do

  resources :events
  resources :users
  resources :static_pages do
    get :search_artist, on: :collection, as: :search_artist
    get :search_zipcode, on: :collection, as: :search_zipcode
  end
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  match '/venues', to: 'static_pages#venues', via: 'get', as: 'venues'
  match '/artists', to: 'static_pages#artist', via: 'get', as: 'artists'
  match '/events', to: 'events#index', via: 'get', as: 'events'
  match '/signin', to: 'sessions#new', via: 'get', as: 'signin'
  match '/signup', to: 'users#new', via: 'get', as: 'signup'
  match '/signout', to: 'sessions#destroy', via: 'get', as: 'signout'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :artist_ids, :artist_names, :date, :ticket_url, :venue_id, :venue_name, :user_id, :event_id
  belongs_to :user

  validates :user_id, presence: true
  validates :venue_name, presence: true
  validates :date, presence: true
  validates :event_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :checkZipCodeLength, only: [:index]

  include ApiEndpoints
  include SessionsHelper
  include UsersHelper

  def checkZipCodeLength
    if params['static_pages']
      @zipcode = params['static_pages']['zipcode']
    else
      @zipcode = params['zipcode']
    end

    if @zipcode && ( @zipcode.length != 5 || !@zipcode.is_i? )
      flash[:error] = ' Invalid Zip Code'
      redirect_to root_path
    end
  end


  def index
    @artistName = params['artistName']
    @artistId = params['artistId']
    
    if !params['static_pages'].nil?
      @zipcode = params['static_pages']['zipcode']
    else
      @zipcode = params['zipcode']
    end

    if !@artistId.nil?

      artist_response = get_events_response_body({'artistId' => @artistId})
      if artist_response
        @events = JSON.parse(artist_response)['Events']
        @events_for_text = 'Listing events for \'' + @artistName + '\''
      else
        @events = nil
        @events_for_text = ""
      end

    elsif !@zipcode.nil?

      event_response = get_events_response_body({'zipCode' => @zipcode})
      if event_response
        @events = JSON.parse(event_response)['Events']
        @events_for_text = 'Listing events in the ' + @zipcode + ' area'
      else
        @events = nil
        @events_for_text = ""
      end

    elsif @artistId.empty? || @zipcode.empty?
      redirect_to :back
    else
      @events = nil
      @events_for_text = ""
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
  
    params.each do |key, value|
      puts "#{key} is #{value}"
    end

    if !current_user.events.find_by_event_id(params['Id'])
      artist_list = []
      params['Artists'].each do |artist|
        artist_list << artist['Name']
      end
      @event = current_user.events.create( event_id: params['Id'], venue_name: params['Venue']['Name'], date: params['Date'], artist_names: artist_list.join(', '))
    end

    respond_to do |format|
      if @event && @event.save
        format.html { 
          if params['artistId']
            redirect_to events_path('artistId' => params['artistId'])
          elsif params['zipCode']
            redirect_to events_path('zipcode' => params['zipCode'])
          else
            redirect_to :back
          end 
        }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { 
          if params['artistId']
            redirect_to events_path('artistId' => params['artistId'])
          elsif params['zipCode']
            redirect_to events_path('zipcode' => params['zipCode'])
          else
            redirect_to :back
          end
        }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy

    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html {
        if params['artistId']
          redirect_to events_path('artistId' => params['artistId'])
        elsif params['zipCode']
          redirect_to events_path('zipcode' => params['zipCode'])
        else
          redirect_to :back
        end
      }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper	
end

app/views/events/_event_list.html.erb
<% if @events %>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><%= @events_for_text %></h3>
        </div>
        <ul class="list-group">
            <% @events.each do |event| %>
                <li class="list-group-item">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h4><strong><%= event['Venue']['Name'] %></strong></h4>
                            <%= event['Venue']['City'] %><br>
                            <%= Time.parse(event['Date']).strftime("%b %d, %Y") %><br>
                            <%= Time.parse(event['Date']).strftime("%l:%M %p") %><br><br>

                            <h5>Performances by: </h5>
                            <ul class="list-group">
                                <% event['Artists'].each do |artist| %>
                                    <li class="no-bullets"><span class="glyphicon glyphicon-chevron-right"></span> <%= artist['Name'] %></li>
                                <% end %>
                            </ul>
                        </div>
                        <div class="panel-footer">
                            <% if signed_in? && !current_user.events.find_by_event_id(event['Id']) %>
                                <%= button_to "Add to favourites", events_path(event), method: :post, class: "btn btn-primary btn-block" %>
                            <% end %>
                            <%= link_to "Get Tickets", event['TicketUrl'], class: "btn btn-default btn-block" %>
                        </div>
                    </div>
                </li>
            <% end %>

            <% if @events.empty? %>
                <li class="list-group-item"><h2 class="text-center">Sorry, no results</h2></li>
            <% end %>
        </ul>
    </div>
<% else %>
    <h2 class="text-center">Sorry, no results</h2>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :venue_name %><br />
    <%= f.text_field :venue_name %>
  </div>
  <div class="field">
    <%= f.label :artist_names %><br />
    <%= f.text_field :artist_names %>
  </div>
  <div class="field">
    <%= f.label :ticket_url %><br />
    <%= f.text_field :ticket_url %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br />
    <%= f.number_field :venue_id %>
  </div>
  <div class="field">
    <%= f.label :artist_ids %><br />
    <%= f.text_field :artist_ids %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_user_favs.html.erb
<% if current_user.events.any? %>
	<h3>Favourite Events</h3>
	<ul class="list-group">
		<% @current_user.events.each do |event| %>
			<li class="list-group-item">
				<h5><strong><%= event.venue_name %></strong></h5>
				<h5><%= Time.parse(event.date).strftime("%b %d, %Y") %></h5>
				<strong>Performances by: </strong><%= event.artist_names %>
				<%= button_to "Remove", event_path(event.id), method: :delete, class: "btn btn-danger btn-xs btn-block" %>

			</li>
		<% end %>
	</ul>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container-fluid">
    <div class="container-fuild">
        <% if signed_in? && has_favorite_events? %>
            <div class="col-md-9">
                <%= render 'event_list' %>
            </div>
            <div class="col-md-3">
                <%= render 'user_favs' %>
            </div>
        <% else %>
            <%= render 'event_list' %>
        <% end %>
    </div>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Venue name:</b>
  <%= @event.venue_name %>
</p>

<p>
  <b>Artist names:</b>
  <%= @event.artist_names %>
</p>

<p>
  <b>Ticket url:</b>
  <%= @event.ticket_url %>
</p>

<p>
  <b>Venue:</b>
  <%= @event.venue_id %>
</p>

<p>
  <b>Artist ids:</b>
  <%= @event.artist_ids %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>