config/routes.rb
GiftsApplication::Application.routes.draw do

  resources :events
  resources :users
  resources :static_pages do
    get :search_artist, on: :collection, as: :search_artist
    get :search_zipcode, on: :collection, as: :search_zipcode
  end
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  match '/venues', to: 'static_pages#venues', via: 'get', as: 'venues'
  match '/artists', to: 'static_pages#artist', via: 'get', as: 'artists'
  match '/events', to: 'events#index', via: 'get', as: 'events'
  match '/signin', to: 'sessions#new', via: 'get', as: 'signin'
  match '/signup', to: 'users#new', via: 'get', as: 'signup'
  match '/signout', to: 'sessions#destroy', via: 'get', as: 'signout'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to 'JamBase App', root_path, :class => 'navbar-brand' %>
		</div>

		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
			</ul>

			<div class="nav navbar-nav navbar-right">
				<ul class="nav navbar-nav navbar-right">
					<% if signed_in? %>
						<li><%= link_to current_user.name, current_user %></li>
						<li><%= link_to 'Sign Out', signout_path %></li>
					<% else %>
						<li><%= link_to 'Sign In', signin_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>JamBase App</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
		<% flash.each do |key, value| %>
	  		<div class="<%= flash_class(key) %> col-md-8 col-md-offset-2">
	  			<%= value %>
	  		</div>
		<% end %>
	</div>

	<%= yield %>

</body>
</html>